// Generated by SimpleVM.GenerateBootstrapFiles

#include <stdlib.h>
#include <stdio.h>
#include "Bootstrap.h"
#include "reader/NodeReader.h"
#include "ObjectMemory.h"


void loadClassesIntoObjectMemory(ObjectMemory * om) {
    loadClassIfAbsent(om, "Object", B_OBJECT);
    loadClassIfAbsent(om, "Behavior", B_BEHAVIOR);
    loadClassIfAbsent(om, "ClassDescription", B_CLASSDESCRIPTION);
    loadClassIfAbsent(om, "Class", B_CLASS);
    loadClassIfAbsent(om, "Metaclass", B_METACLASS);
    loadClassIfAbsent(om, "Boolean", B_BOOLEAN);
    loadClassIfAbsent(om, "False", B_FALSE);
    loadClassIfAbsent(om, "True", B_TRUE);
    loadClassIfAbsent(om, "Collection", B_COLLECTION);
    loadClassIfAbsent(om, "SequenceableCollection", B_SEQUENCEABLECOLLECTION);
    loadClassIfAbsent(om, "ArrayedCollection", B_ARRAYEDCOLLECTION);
    loadClassIfAbsent(om, "Array", B_ARRAY);
    loadClassIfAbsent(om, "ByteArray", B_BYTEARRAY);
    loadClassIfAbsent(om, "CharacterArray", B_CHARACTERARRAY);
    loadClassIfAbsent(om, "String", B_STRING);
    loadClassIfAbsent(om, "AsciiString", B_ASCIISTRING);
    loadClassIfAbsent(om, "Magnitude", B_MAGNITUDE);
    loadClassIfAbsent(om, "ArithmeticValue", B_ARITHMETICVALUE);
    loadClassIfAbsent(om, "Number", B_NUMBER);
    loadClassIfAbsent(om, "Integer", B_INTEGER);
    loadClassIfAbsent(om, "SmallInteger", B_SMALLINTEGER);
    loadClassIfAbsent(om, "Character", B_CHARACTER);
    loadClassIfAbsent(om, "Stream", B_STREAM);
    loadClassIfAbsent(om, "PositionableStream", B_POSITIONABLESTREAM);
    loadClassIfAbsent(om, "ReadStream", B_READSTREAM);
    loadClassIfAbsent(om, "UndefinedObject", B_UNDEFINEDOBJECT);
}
